apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: github-vamshi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: public.ecr.aws/z7k4r2x1/github-vamshi/my-app
        ports:
        - containerPort: 8080
