apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-app-deployment
  labels:
    app: form-app
spec:
  replicas: 2  # Adjust to desired number of replicas
  selector:
    matchLabels:
      app: form-app
  template:
    metadata:
      labels:
        app: form-app
    spec:
      containers:
        - name: form-app
          image: <your-docker-image>:latest  # Replace with actual image name
          ports:
            - containerPort: 8080
