apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: github-vamshi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: 971901834334.dkr.ecr.eu-north-1.amazonaws.com/github/vamshi:latest
        ports:
        - containerPort: 8080
