apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: github-vamshi
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30515
  type: NodePort
