apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: default
spec:
  type: LoadBalancer  # Enables external access and automatic load balancer creation
  selector:
    app: my-app       # Ensure your pods have this label
  ports:
    - protocol: TCP
      port: 80        # Port to expose externally
      targetPort: 8080  # Port your app listens on inside the pod
