apiVersion: v1
kind: Service
metadata:
  name: form-app-service
spec:
  selector:
    app: form-app
  ports:
    - protocol: TCP
      port: 80  # Exposing port 80
      targetPort: 8080  # Mapping it to container's internal port 8080
  type: LoadBalancer  # Exposes the service externally (cloud-based)

