apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: github-vamshi
spec:
  selector:
    app: my-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080          # service port
      targetPort: 8080    # pod container port
      nodePort: 30080     # port on node to access externally (must be 30000-32767)
